version: "2"
run:
  allow-parallel-runners: true
linters:
  default: standard
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    lll:
      line-length: 256
    gocyclo:
      min-complexity: 15
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        path: api/*
      - linters:
          - dupl
          - lll
          - funlen
        path: internal/*
      - path: _test\.go
        linters:
          - dupl
          - funlen
          - gosec
          - errcheck
      - path: cmd/
        linters:
          - gocyclo
      - path: internal/controller/valkey_controller\.go
        linters:
          - gocyclo
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
